<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BusTicketPlatform.Payment.Application</RootNamespace>
    <Description>Payment use cases and ports. No controllers or ORM mapping.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BusTicketPlatform.Payment.Domain\BusTicketPlatform.Payment.Domain.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\BusTicketPlatform.BuildingBlocks\BusTicketPlatform.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
