<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>BusTicketPlatform.Identity.Api</RootNamespace>
    <Description>Identity HTTP composition root.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BusTicketPlatform.Identity.Application\BusTicketPlatform.Identity.Application.csproj" />
    <ProjectReference Include="..\BusTicketPlatform.Identity.Infrastructure\BusTicketPlatform.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\BusTicketPlatform.BuildingBlocks.AspNetCore\BusTicketPlatform.BuildingBlocks.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
</Project>
